server:
  port: 8080
spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    #    url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://10.57.26.131:3306/smartroad?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&verifyServerCertificate=false&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 20
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 'ZTM' FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false


mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: cn.tongdun.mybatis.model
